POST https://poker.evenbetpoker.com/api/web/v2/login?clientId=default
Content-Type: application/json

{
    "clientId": "default", 
    "login": "richard",
    "password": "poker"
}

###

GET https://poker.evenbetpoker.com/api/web/v2/casino/games?clientId=default
Content-Type: application/json

###

POST https://poker.evenbetpoker.com/api/web/auth/token?clientId=default
Content-Type: application/json

{
    "clientId": "default", 
    "refreshToken": "REF336FDE62BB00E0B4FA3EB68ACA590CAF"
}

###

GET https://poker.evenbetpoker.com/api/web/v2/users/me/balance?clientId=default&auth=API7419606FDB1594F7FA21F924D462E3A5

###

POST https://poker.evenbetpoker.com/api/web/v2/casino/games/544816/session-demo?clientId=default
Content-Type: application/json

{
    "clientId": "default", 
    "gameId": "544816"
}

###