POST https://poker.evenbetpoker.com/api/web/v2/login?clientId=default
Content-Type: application/json

{
    "clientId": "default", 
    "login": "richard",
    "password": "poker"
}

###

GET https://poker.evenbetpoker.com/api/web/v2/casino/games?clientId=default
Content-Type: application/json

###

POST https://poker.evenbetpoker.com/api/web/auth/token?clientId=default
Content-Type: application/json

{
    "clientId": "default", 
    "refreshToken": "REF336FDE62BB00E0B4FA3EB68ACA590CAF"
}

###